### ISSUE TITLE
Refactoring 30.03.2020

### ISSUE THREAD

**Issue by ashvidchenko** [tolmadima/LastFm#13]
- allow not https network request in the manifest file
- remove the folder ".idea" from the repo
- remove objectbox from the list of libraries
- shorten the name of id "artistsRecyclerView", use prefix instead "RecyclerView"
- use prefix with the type of view in the name of ids "artist_name", "artist_playcount"
- In the adapter there is a function called "setItems". Its functionality doesn't match its name.
- use hungarian name notation everywhere or don't use it at all
- the field "onArtistListener" of ArtistViewHolder must be private
- don't use the link to a view holder (itemView.setOnClickListener(this);)
- ArtistsDeserializer must not use any external resources from MainActivity. Create constants for raw strings.
- numberArtists -> count
- requestedArtists -> artists
- in MainActivity refactor all static fields to non-static ones
- don't create long line of code, break them on several lines (for example, MainActivity)
- use method subscribe with previous code
- artistsRecyclerView -> rvArtists
- remove switch operator from the click listener in MainActivity
- rename the variable "button" in MainActivity
- ArtistScreen -> ArtistInfoActivity
- create static method getInstance and static field "instance" in ServiceGenerator, other fields and methods must be non-static

**Comment by tolmadima** [comment]
android:usesCleartextTraffic="true" added to manifest
Removed folder .idea from the repo, also added it files to gitignore file
Objectbox were deleted.
Changed name artistRecycleView -> rvArtist
Changed names artist_name and artist_playcount
Changed setItems to addItems
Changed field "onArtistListener" of ArtistViewHolder to private
Moved static constants from MainActivity to ArtistDeserializer
numberArtists -> count requestedArtists -> artists - fixed in current branch in working process
Moved all static lines that were used in another classes, in rest deleted static parameter
Splited all long lines of code
renamed button
Changed ArtistScreen to ArtistInfoActivity
Was fixed in anotherbranch in working process
